In [75]:
import numpy as np
import pandas as pd

def crossproduct(x):
    n,p = x.shape
    center = np.average(x,0)
    x = x - center
    return x.T@x

iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
x = iris.loc[50:99, "sepal_length":"petal_width"]

A = crossproduct(x).to_numpy()
print(A)

[[13.0552  4.174   8.962   2.7332]
 [ 4.174   4.825   4.05    2.019 ]
 [ 8.962   4.05   10.82    3.582 ]
 [ 2.7332  2.019   3.582   1.9162]]


In [76]:
S = A / (x.shape[0] - 1)
print(S)

[[0.26643265 0.08518367 0.18289796 0.05577959]
 [0.08518367 0.09846939 0.08265306 0.04120408]
 [0.18289796 0.08265306 0.22081633 0.07310204]
 [0.05577959 0.04120408 0.07310204 0.03910612]]


In [77]:
cov_x = np.cov(x, rowvar=0, bias=0)
print(cov_x)

[[0.26643265 0.08518367 0.18289796 0.05577959]
 [0.08518367 0.09846939 0.08265306 0.04120408]
 [0.18289796 0.08265306 0.22081633 0.07310204]
 [0.05577959 0.04120408 0.07310204 0.03910612]]


In [78]:
def eig_sort(X):
    eig_value, eig_vector = np.linalg.eig(X)
    index = eig_value.argsort()[::-1]
    eig_value_sort = eig_value[index]
    eig_vector_sort = eig_vector.T[index]
    return (eig_value_sort, eig_vector_sort.T)

In [79]:
eig_sort(S)


(array([0.48787394, 0.0723841 , 0.05477609, 0.00979036]),
 array([[ 0.68672376,  0.66908906, -0.26508336,  0.1022796 ],
        [ 0.30534703, -0.56746531, -0.72961786, -0.22891939],
        [ 0.62366312, -0.34332698,  0.62716496, -0.31596679],
        [ 0.21498369, -0.33530513,  0.06366081,  0.91504087]]))

In [80]:
cor_S = pd.DataFrame(S).corr()
eig_sort(cor_S)

(array([2.87940902e+00, 7.99051396e-01, 3.21539584e-01, 1.35169661e-17]),
 array([[ 0.52387658,  0.00342952, -0.8076627 ,  0.27059662],
        [ 0.32541998, -0.92412055,  0.19863762, -0.02541945],
        [ 0.57341934,  0.24771336,  0.11416639, -0.77252468],
        [ 0.53930087,  0.29090813,  0.54331399,  0.57387886]]))

In [81]:
corr_S = np.corrcoef(S)
eig_sort(corr_S)

(array([2.87940902e+00, 7.99051396e-01, 3.21539584e-01, 2.87402566e-17]),
 array([[ 0.52387658,  0.00342952, -0.8076627 ,  0.27059662],
        [ 0.32541998, -0.92412055,  0.19863762, -0.02541945],
        [ 0.57341934,  0.24771336,  0.11416639, -0.77252468],
        [ 0.53930087,  0.29090813,  0.54331399,  0.57387886]]))