In [137]:
import numpy as np
import pandas as pd

def crossproduct(x):
    n,p = x.shape
    center = np.average(x,0)
    x = x - center
    return x.T@x

iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
x = iris.loc[50:99, "sepal_length":"petal_width"]

A = crossproduct(x)
list_A = A.to_numpy().tolist()
print(list_A)

[[13.055200000000005, 4.1739999999999995, 8.962000000000005, 2.7332], [4.1739999999999995, 4.825000000000001, 4.050000000000002, 2.019], [8.962000000000005, 4.050000000000002, 10.820000000000006, 3.582], [2.7332, 2.019, 3.582, 1.9161999999999992]]


In [138]:
S = A /(x.shape[0] - 1)
list_S = S.to_numpy().tolist()
print(list_S)

[[0.2664326530612246, 0.08518367346938774, 0.18289795918367358, 0.0557795918367347], [0.08518367346938774, 0.09846938775510206, 0.08265306122448983, 0.041204081632653065], [0.18289795918367358, 0.08265306122448983, 0.22081632653061237, 0.07310204081632653], [0.0557795918367347, 0.041204081632653065, 0.07310204081632653, 0.039106122448979576]]


In [139]:
cov_x = np.cov(x, rowvar=0, bias=0)
print(cov_x)

[[0.26643265 0.08518367 0.18289796 0.05577959]
 [0.08518367 0.09846939 0.08265306 0.04120408]
 [0.18289796 0.08265306 0.22081633 0.07310204]
 [0.05577959 0.04120408 0.07310204 0.03910612]]


In [140]:
def eig_sort(X):
    eig_value, eig_vector = np.linalg.eig(X)
    index = eig_value.argsort()[::-1]
    eig_value_sort = eig_value[index]
    eig_vector_sort = eig_vector.T[index]
    return (eig_value_sort, eig_vector_sort.T)

In [141]:
eig_sort(S)


(array([0.48787394, 0.0723841 , 0.05477609, 0.00979036]),
 array([[ 0.68672376,  0.66908906, -0.26508336,  0.1022796 ],
        [ 0.30534703, -0.56746531, -0.72961786, -0.22891939],
        [ 0.62366312, -0.34332698,  0.62716496, -0.31596679],
        [ 0.21498369, -0.33530513,  0.06366081,  0.91504087]]))

In [142]:
cor_S = S.corr()
eig_sort(cor_S)

(array([ 2.87940902e+00,  7.99051396e-01,  3.21539584e-01, -5.06651832e-17]),
 array([[ 0.52387658,  0.00342952, -0.8076627 ,  0.27059662],
        [ 0.32541998, -0.92412055,  0.19863762, -0.02541945],
        [ 0.57341934,  0.24771336,  0.11416639, -0.77252468],
        [ 0.53930087,  0.29090813,  0.54331399,  0.57387886]]))