In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.datasets as datasets
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [34]:
iris = datasets.load_iris()
df = pd.DataFrame(data = iris.data[50:100, :], columns = iris.feature_names)

scaler = StandardScaler()
scaler.fit(df) 
iris_scaled = scaler.transform(df)

In [35]:
pca1 = PCA(n_components =1)
PCscore1 = pca1.fit_transform(iris_scaled)
PCInverse1 = pca1.inverse_transform(PCscore1)
print(PCInverse1)

[[ 1.1325808   1.09152951  1.25511961  1.21009127]
 [ 0.8755404   0.84380574  0.97026889  0.93545979]
 [ 1.25268858  1.20728389  1.38822237  1.33841888]
 [-0.71483206 -0.6889224  -0.79217282 -0.76375304]
 [ 0.68778826  0.66285883  0.76220304  0.73485845]
 [ 0.01420433  0.01368948  0.01574116  0.01517643]
 [ 1.13999867  1.09867852  1.26334005  1.21801681]
 [-1.68467901 -1.62361649 -1.86695171 -1.79997346]
 [ 0.55155269  0.53156122  0.61122755  0.58929932]
 [-0.49116656 -0.47336384 -0.54430799 -0.52478054]
 [-1.81701033 -1.75115135 -2.01360052 -1.94136114]
 [ 0.33728729  0.32506204  0.37377986  0.36037023]
 [-0.94027542 -0.90619439 -1.04200788 -1.00462509]
 [ 0.50630277  0.48795142  0.56108185  0.54095263]
 [-0.45793582 -0.44133757 -0.50748187 -0.48927559]
 [ 0.757559    0.73010067  0.83952258  0.80940409]
 [ 0.36696565  0.35366468  0.40666924  0.39207969]
 [-0.61503444 -0.59274203 -0.68157767 -0.65712557]
 [ 0.06273187  0.0604581   0.0695191   0.06702505]
 [-0.83431321 -0.80407286 -0.92

In [36]:
pca2 = PCA(n_components =2)
PCscore2 = pca2.fit_transform(iris_scaled)
PCInverse2 = pca2.inverse_transform(PCscore2)
print(PCInverse2)

[[ 1.4525117   0.73913137  1.41584482  1.06181816]
 [ 0.58850433  1.15997081  0.82606921  1.06848767]
 [ 1.62415101  0.7981247   1.57483573  1.1662633 ]
 [-0.49321273 -0.9330321  -0.68083686 -0.86646331]
 [ 1.04319089  0.27138922  0.94074837  0.57014584]
 [-0.0781281   0.11539199 -0.03064433  0.05796822]
 [ 0.63992516  1.64950051  1.01211573  1.44977765]
 [-2.05047419 -1.22069968 -2.05071798 -1.63044439]
 [ 1.02432465  0.01081139  0.84873627  0.37019147]
 [-1.14632937  0.24828623 -0.87344527 -0.22114301]
 [-1.50007707 -2.10024764 -1.85438125 -2.08824498]
 [-0.17110408  0.885046    0.11837685  0.59598602]
 [ 0.04364768 -1.98996802 -0.54770972 -1.46062775]
 [ 0.56598798  0.42220924  0.5910662   0.51329131]
 [-1.11817133  0.28589998 -0.83916755 -0.1832871 ]
 [ 0.86987214  0.60638976  0.89594587  0.75735217]
 [-0.23958958  1.02177437  0.10195119  0.67318986]
 [-0.39826608 -0.83150849 -0.57267871 -0.75758764]
 [ 0.95251865 -0.91962604  0.51652554 -0.34534979]
 [-0.66789876 -0.98737538 -0.84